# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from validator import node_pb2 as validator_dot_node__pb2
from validator import service_pb2 as validator_dot_service__pb2


class ValidatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddNodes = channel.unary_unary(
                '/ValidatorService/AddNodes',
                request_serializer=validator_dot_service__pb2.AddNodesRequest.SerializeToString,
                response_deserializer=validator_dot_node__pb2.ValidatorList.FromString,
                )
        self.DelNodes = channel.unary_unary(
                '/ValidatorService/DelNodes',
                request_serializer=validator_dot_service__pb2.DelNodesRequest.SerializeToString,
                response_deserializer=validator_dot_node__pb2.ValidatorList.FromString,
                )


class ValidatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNodes,
                    request_deserializer=validator_dot_service__pb2.AddNodesRequest.FromString,
                    response_serializer=validator_dot_node__pb2.ValidatorList.SerializeToString,
            ),
            'DelNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.DelNodes,
                    request_deserializer=validator_dot_service__pb2.DelNodesRequest.FromString,
                    response_serializer=validator_dot_node__pb2.ValidatorList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ValidatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ValidatorService/AddNodes',
            validator_dot_service__pb2.AddNodesRequest.SerializeToString,
            validator_dot_node__pb2.ValidatorList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ValidatorService/DelNodes',
            validator_dot_service__pb2.DelNodesRequest.SerializeToString,
            validator_dot_node__pb2.ValidatorList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
